'use client';

import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import Link from 'next/link';

interface SharedIdea {
  title: string;
  summary: string;
  category: string;
  location: string;
  framework: { sections: Array<{ id: string; title: string; icon: string; description: string; questions: string[]; priority: string }> };
  research: Record<string, { content: string; keyInsights?: string[]; score?: number; risks?: string[]; opportunities?: string[] }>;
  analysis: Record<string, unknown> | null;
  created_at: string;
}

export default function SharePage() {
  const params = useParams();
  const [idea, setIdea] = useState<SharedIdea | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    fetch(`/api/share/${params.shareId}`)
      .then(res => {
        if (!res.ok) throw new Error('Not found');
        return res.json();
      })
      .then(setIdea)
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, [params.shareId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-neutral-950">
        <div className="animate-pulse text-neutral-400">Loading shared research...</div>
      </div>
    );
  }

  if (error || !idea) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-neutral-950 text-white">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-2">Research Not Found</h1>
          <p className="text-neutral-400 mb-6">This shared link may have expired or been removed.</p>
          <Link href="/" className="text-amber-400 hover:text-amber-300">← Go to MarketMind</Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      <header className="border-b border-neutral-800 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xl font-bold">📊 MarketMind</span>
            <Badge variant="secondary" className="bg-neutral-800 text-neutral-400">Shared Research</Badge>
          </div>
          <Link href="/" className="text-amber-400 hover:text-amber-300 text-sm">
            Try MarketMind →
          </Link>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">{idea.title}</h1>
          <div className="flex gap-3 items-center">
            <Badge className="bg-amber-500/20 text-amber-300">{idea.category}</Badge>
            {idea.location && <span className="text-sm text-neutral-400">📍 {idea.location}</span>}
            <span className="text-sm text-neutral-500">{new Date(idea.created_at).toLocaleDateString()}</span>
          </div>
          <p className="text-neutral-300 mt-4 leading-relaxed">{idea.summary}</p>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          {idea.framework?.sections?.map((section) => {
            const research = idea.research?.[section.id];
            return (
              <Card key={section.id} className={`border-neutral-800 bg-neutral-900/50 ${research ? 'border-l-2 border-l-green-500/50' : ''}`}>
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <span className="text-xl">{section.icon}</span>
                    {section.title}
                    {research?.score && (
                      <Badge className="ml-auto bg-amber-500/20 text-amber-300">{research.score}/10</Badge>
                    )}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {research ? (
                    <div className="space-y-3">
                      {research.keyInsights?.map((insight, i) => (
                        <p key={i} className="text-sm text-neutral-300">• {insight}</p>
                      ))}
                      <div className="text-sm text-neutral-400 whitespace-pre-wrap line-clamp-6">{research.content}</div>
                    </div>
                  ) : (
                    <p className="text-sm text-neutral-500">Not yet researched</p>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      </main>

      <footer className="border-t border-neutral-800 py-8 text-center text-sm text-neutral-500 mt-12">
        Generated by <Link href="/" className="text-amber-400 hover:text-amber-300">MarketMind</Link> — AI-Powered Business Research
      </footer>
    </div>
  );
}
